version: "3"
services:
  conjur:
    image: registry2.itci.conjur.net/conjur-appliance:5.7.2-20200311203146-4e85e30
    ports:
      - "443:443"
      - "444:444"
    security_opt:
        - "seccomp:./seccomp.json"
    volumes:
      - ./config:/opt/config

  client:
    image: cyberark/conjur-cli:5
    working_dir:  -w /src/cli
    environment:
      CONJUR_APPLIANCE_URL: https://conjur
      CONJUR_ACCOUNT: demo
      CONJUR_AUTHN_LOGIN: admin
    links:
      - conjur:conjur
    volumes:
      - .:/src/cli
      - ./cli_cache:/root
