version: "3"
services:
  conjur:
    image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
    ports:
      - "443:443"
    security_opt:
        - "seccomp:unconfined"
    # volumes:
    #   - certs:/opt/conjur/etc/ssl

  client:
    image: conjurinc/cli5
    working_dir:  -w /src/cli
    environment:
      CONJUR_APPLIANCE_URL: https://conjur
      CONJUR_ACCOUNT: demo
      CONJUR_AUTHN_LOGIN: admin
    links:
      - conjur:conjur
    volumes:
      - .:/src/cli
      - ./cli_cache:/root
      # - certs:/opt/conjur/etc/ssl

volumes:
  certs:
