version: "3"
services:
  conjur-master-1:
    image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
    ports:
      - "443:443"
    expose:
      - "443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - certs:/opt/conjur/etc/ssl
      - backups:/opt/conjur/backup/

  conjur-master-2:
    image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
    ports:
      - "444:443"
    expose:
      - "443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - certs:/opt/conjur/etc/ssl
      - backups:/opt/conjur/backup/

  conjur-master-3:
    image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
    ports:
      - "445:443"
    expose:
      - "443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - certs:/opt/conjur/etc/ssl
      - backups:/opt/conjur/backup/

  conjur-master-4:
    image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
    ports:
      - "446:443"
    expose:
      - "443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - certs:/opt/conjur/etc/ssl
      - backups:/opt/conjur/backup/

  client:
    image: cyberark/conjur-cli:5
    working_dir:  -w /src/cli
    environment:
      CONJUR_APPLIANCE_URL: https://conjur-master-1
      CONJUR_ACCOUNT: demo
      CONJUR_AUTHN_LOGIN: admin
    # links:
    #   - conjur-master-1
    volumes:
      - .:/src/cli
      - ./cli_cache:/root
      - certs:/opt/conjur/etc/ssl

volumes:
  certs:
  backups:
