version: "3"
services:
  conjur-master.mycompany.local:
    image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
    ports:
      - "443:443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - backups:/opt/conjur/backup/
      - ./files:/conjur_files
    links:
      - ldap-server

  conjur-follower.mycompany.local:
    image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
    ports:
      - "444:443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - backups:/opt/conjur/backup/
      - ./files:/conjur_files
    links:
      - ldap-server

  client:
    image: cyberark/conjur-cli:5
    working_dir:  -w /src/cli
    environment:
      CONJUR_APPLIANCE_URL: https://conjur-master.mycompany.local
      CONJUR_ACCOUNT: demo
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - .:/src/cli
      - ./cli_cache:/root
    

  ldap-server:
    image: osixia/openldap
    command: --copy-service --loglevel debug
    environment:
      LDAP_ADMIN_PASSWORD: ldapsecret

    volumes:
      - ./files/ldap:/opt/ldap


volumes:
  backups:
