version: "3"
services:
  conjur-master:
    image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
    ports:
      - "443:443"
    expose:
      - "443"
      - "5432"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - backups:/opt/conjur/backup/

  conjur-follower:
    image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
    expose:
      - "443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - backups:/opt/conjur/backup/

  conjur-standby:
    image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
    expose:
      - "443"
      - "5432"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - backups:/opt/conjur/backup/

  client:
    image: cyberark/conjur-cli:5
    working_dir:  -w /src/cli
    environment:
      CONJUR_APPLIANCE_URL: https://conjur-master-1
      CONJUR_ACCOUNT: demo
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - .:/src/cli
      - ./cli_cache:/root

volumes:
  backups:
