version: '3'
services:
  conjur-master:
    image: registry.tld/conjur-appliance:policy-factory
    ports:
      - 5443:443
    security_opt:
          - "seccomp:unconfined"

  client:
    image: cyberark/conjur-cli:5
    working_dir: /src
    environment:
      CONJUR_APPLIANCE_URL: https://conjur-master
      CONJUR_ACCOUNT: demo
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - .:/src
      - ./tmp/cache/client:/root
